File management firmware update
Wolkabout/WolkConnect-Java pull request #53
Opened 2020-11-02 14:51 UTC by nvuletic

This pull requests adds the functionality into the WolkConnect Java for File Management and Firmware Update as of the WolkAbout IoT Platform version 20.GA.

2020-11-03 16:10 UTC, milanzlicic requested changes

2020-11-04 09:22 UTC, milanzlicic requested changes

2020-11-04 09:22 UTC, milanzlicic commented on src/main/java/com/wolkabout/wolk/Wolk.java
> +            fileManagementEnabled = true;
Does this have any use if the location is null?

2020-11-04 09:45 UTC, milanzlicic commented
Make publishing and persisting logic is not consistent with other connectors.
Encapsulate mqtt client with some class that subscribes to all topics with same QOS

2020-11-04 15:08 UTC, nvuletic commented on src/main/java/com/wolkabout/wolk/firmwareupdate/model/device2platform/UpdateStatus.java
> +    @JsonInclude(JsonInclude.Include.NON_NULL)
This annotation only says to include the value in the payload, if the value is not null. And only one of the constructors set it to null, this cleans up the payload to only contain what you need, as the error field should not appear in the message if it is not set.

Null if a non-error status is being set, as that payload should not have even the `"error": null` field in JSON.
The error constructor will set it, and only then will it show up in the payload.

2020-11-04 15:11 UTC, nvuletic commented on src/main/java/com/wolkabout/wolk/firmwareupdate/FirmwareUpdateProtocol.java
> +    protected static final int QOS = 0;
We don't have a MQTT client encapsulation. But I figure we could create some static utility class to store the value for us.

2020-11-06 08:28 UTC, nvuletic commented on src/main/java/com/wolkabout/wolk/Wolk.java
> +            fileManagementEnabled = true;
Yes, it will use the default one. I have just put it as a final value in the class.

2020-11-09 07:34 UTC, nvuletic commented on src/main/java/com/wolkabout/wolk/firmwareupdate/FirmwareInstaller.java
> +}
This has been refactored in an interface. From now on, the interface only takes in the firmware version as return value for the implemented method, has a `void onAbortCommandReceived()`, and a `boolean onInitializeCommandReceived(String fileName)`, that will if returned true record the current firmware version. On next startup it will read the written firmware version and compare it with current one in runtime, if they're different, it reports a successful status, and if not, a failure. This is the same way that the [`WolkConnect-Python`](https://github.com/Wolkabout/WolkConnect-Python) works.

2020-11-09 14:02 UTC, milanzlicic approved these changes

2020-11-09 14:03 UTC, merged